# Generated by Django 3.2.8 on 2021-10-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amigos',
            name='Cidade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='amigos',
            name='Nome',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='amigos',
            name='Obs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='amigos',
            name='Telefone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
