# Generated by Django 3.2.8 on 2021-10-30 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20211030_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(blank=True, max_length=50)),
                ('Cidade', models.CharField(blank=True, max_length=50)),
                ('Telefone', models.CharField(blank=True, max_length=10)),
                ('Empresa', models.CharField(blank=True, max_length=50)),
                ('Obs', models.TextField(blank=True)),
            ],
        ),
    ]
