# Generated by Django 3.2.8 on 2021-10-31 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_família'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amigos',
            name='Telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='família',
            name='Telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='trabalho',
            name='Telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
